SELECT      
ENT.NOME AS NOME_CLIENTE,
ENT.ENTIDADE,
ENT.GRUPO,
FAT.PEDIDO,
FAT.DATA,
FAT.GERAL,
ALX.ALMOXARIFADO,
FAT.EMISSAO,
MVT.DESCRICAO AS NATUREZA,
FAT.INICIAL AS NNOTA,
VED.GRUPO AS GRUPO_VENDEDOR,
VED.ENTIDADE AS ENTIDADE_VENDEDOR,
VED.NOME AS NOME_VENDEDOR
FROM ALC_FATURA AS FAT
LEFT JOIN PAD_ENTIDADE AS ENT
ON ENT.ENTIDADE = FAT.ENTIDADE
LEFT JOIN ALC_ITEFAT AS ITF
ON ITF.FATURAID = FAT.FATURAID
LEFT JOIN ALC_TIPO AS MVT
ON MVT.ES = FAT.ES AND MVT.TIPO = FAT.TIPO
LEFT JOIN PAD_ALMOXARIFADO AS ALX
ON ALX.ALMOXARIFADO = FAT.ALMOXARIFADO
LEFT JOIN PAD_ENTIDADE AS VED
ON VED.ENTIDADE = FAT.VENDEDOR AND VED.GRUPO = FAT.GRUPOVENDEDOR
LEFT JOIN  ALC_ITEM AS ITE
ON ITE.ITEM = ITF.ITEM
WHERE
FAT.DATA BETWEEN $P{p_datade} AND $P{p_dataate}
ORDER BY DATA, ENTIDADE
;