CREATE TABLE CATEGORIA(
    ID BIGINT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE GENERATOR GEN_ID_SEQUENCE_CATEGORIA;

SET TERM ^^ ;

CREATE TRIGGER BI_CATEGORIA FOR CATEGORIA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE_CATEGORIA;
END
^^

SET TERM ; ^^