INSERT INTO CATEGORIA (NOME) VALUES ('Lazer');
INSERT INTO CATEGORIA (NOME) VALUES ('Alimentação');
INSERT INTO CATEGORIA (NOME) VALUES ('Supermecado');
INSERT INTO CATEGORIA (NOME) VALUES ('Farmácia');
INSERT INTO CATEGORIA (NOME) VALUES ('Outros');
