CREATE TABLE PESSOA(
    ID BIGINT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ATIVO SMALLINT NOT NULL,
    LOGRADOURO VARCHAR(30),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(30),
    BAIRRO VARCHAR(30),
    CEP VARCHAR(30),
    CIDADE VARCHAR(30),
    ESTADO VARCHAR(30),
    PRIMARY KEY(ID)
);

CREATE GENERATOR GEN_ID_SEQUENCE_PESSOA;

SET TERM ^^ ;

CREATE TRIGGER BI_PESSOA FOR PESSOA
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE_PESSOA;
END
^^

SET TERM ; ^^