CREATE TABLE lancamento (
	id BIGINT PRIMARY KEY,
	descricao VARCHAR(50) NOT NULL,
	data_vencimento TIMESTAMP NOT NULL,
	data_pagamento TIMESTAMP,
	valor DECIMAL(10,2) NOT NULL,
	observacao VARCHAR(100),
	tipo VARCHAR(20) NOT NULL,
	id_categoria BIGINT NOT NULL,
	id_pessoa BIGINT NOT NULL,
	FOREIGN KEY (id_categoria) REFERENCES categoria(id),
	FOREIGN KEY (id_pessoa) REFERENCES pessoa(id)
);

CREATE GENERATOR GEN_ID_SEQUENCE_LANCAMENTO;

SET TERM ^^ ;

CREATE TRIGGER BI_LANCAMENTO FOR LANCAMENTO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE_LANCAMENTO;
END
^^

SET TERM ; ^^
