CREATE TABLE PROPRIETARIO (
    ID BIGINT NOT NULL,
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE PROPRIETARIO ADD CONSTRAINT UK_PROPRIETARIO UNIQUE (EMAIL);

CREATE GENERATOR GEN_ID_SEQUENCE;

SET TERM ^^ ;

CREATE TRIGGER BI_PROPRIETARIO FOR PROPRIETARIO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE;
END
^^

SET TERM ; ^^
