CREATE TABLE VEICULO (
    ID BIGINT NOT NULL,
    PROPRIETARIO_ID BIGINT NOT NULL,
    MARCA VARCHAR(20) NOT NULL,
    MODELO VARCHAR(20) NOT NULL,
    PLACA VARCHAR(7) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_APREENSAO TIMESTAMP,

    PRIMARY KEY (ID)
);

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_PROPRIETARIO
FOREIGN KEY (PROPRIETARIO_ID) REFERENCES PROPRIETARIO(ID);

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO UNIQUE(PLACA);

CREATE GENERATOR GEN_ID_SEQUENCE_VEICULO;

SET TERM ^^ ;

CREATE TRIGGER BI_VEICULO FOR VEICULO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE_VEICULO;
END
^^

SET TERM ; ^^
