CREATE TABLE AUTUACAO(
    ID BIGINT NOT NULL,
    VEICULO_ID BIGINT NOT NULL,
    DESCRICAO BLOB NOT NULL,
    VALOR_MULTA DECIMAL(10,2) NOT NULL,
    DATA_OCORRENCIA TIMESTAMP NOT NULL,

    PRIMARY KEY(ID)
);

ALTER TABLE AUTUACAO ADD CONSTRAINT FK_AUTUACAO_VEICULO
FOREIGN KEY (VEICULO_ID) REFERENCES VEICULO(ID);

CREATE GENERATOR GEN_ID_SEQUENCE_AUTUACAO;

SET TERM ^^ ;

CREATE TRIGGER BI_AUTUACAO FOR AUTUACAO
BEFORE INSERT
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ID_SEQUENCE_AUTUACAO;
END
^^

SET TERM ; ^^
